name: CI-CD

on:
  push:

jobs:

  lint:
    name: Run linting checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        cache: true
    
    - name: Setup luau-lsp
      uses: ./.github/luau-lsp-setup

    - name: Lint setup
      run: make lint-setup

    - name: Lint
      run: make lint

  publish:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: lint

    environment: 
      name: testing
      url: "https://www.roblox.com/games/${{vars.START_PLACE_ID}}"

    name: Build place and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        cache: true

    - name: Build
      run: make build-place

    # - name: Publish Start Place
    #  uses: Ulferno/upload-to-roblox@latest
     # with:
      #  universeId: ${{ vars.UNIVERSE_ID }}
      #  placeId: ${{ vars.START_PLACE_ID }}
      #  api-key: ${{ secrets.RBX_API_KEY }}
      #  file: build/start_place.rbxl
    
    - name: Publish Destination Place
      uses: Ulferno/upload-to-roblox@latest
      with:
        universeId: ${{ vars.UNIVERSE_ID }}
        placeId: ${{ vars.DESTINATION_PLACE_ID }}
        api-key: ${{ secrets.RBX_API_KEY }}
        file: build/destination_place.rbxl
